config/routes.rb
Rails.application.routes.draw do
  get 'infomations/index'
  devise_for :users
  root to: "events#index"
  get 'events/search'
  resources :events do
    resources :comments, only: :create
  end
  resources :users
  resources :notifications, only: [:index, :destroy]
  
  controller :report do
    get 'report' => 'report#index', as: :report
    get 'report/output', as: :output_report
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope->{order(created_at: :desc)}

  belongs_to :event, optional: true
  belongs_to :comment, optional: true
  belongs_to :visitor, class_name: 'User', optional: true
  belongs_to :visited, class_name: 'User', optional: true

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = current_user.passive_notifications
    if @notifications != nil
      @notifications.where(checked: false).each do |notification|
        notification.update_attributes(checked: true)
      end
    else
      redirect_to root_path
    end
  end

  def destroy
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper

  # def unchecked_notifications
  #   @notifications = current_user.passive_notifications.where(checked: false)
  # end

  def notification_form(notification)
    # @comment = nil
    @visitor = link_to notification.visitor.name, notification.visitor, style:"font-weight: bold;"
    @your_post = link_to 'あなたの予定', event_path(notification.event_id), style:"font-weight: bold;"

    case notification.action
      when "comment" then
        tag.a(@visitor) + 'が' + tag.a(@your_post) + 'にコメントしました'
    end
  end

end

app/views/notifications/_notification.html.erb
<div class="notification-view">
  <%= notification_form(notification) %><span class="moderate-font"><%= " (#{time_ago_in_words(notification.created_at)}ago)" %></span>
  <br>
  <% if !@comment.nil? %>
    <p class="notification-comment"><%= @comment %></p>
  <% end %>
</div>

app/views/notifications/index.html.erb
<div class="main-container">
    <div class="sub-container">
        <h3 class="text-center">
            Notifications
            <span class="notification-span">(コメント通知)</span>
        </h3>
            <%= link_to "Delete notification", notification_path(@notifications), method: :delete ,class: "fas fa-trash" %>
            <hr>
        <% if @notifications.exists? %>
            <div class="users-index">
                <%= render @notifications %> 
            </div>
        <% else %>
            <p>通知はありません</p>
        <% end %>
        <hr>
        <div class="actions report-return">
        <%= link_to "return Top", root_path, class: "return-top" %>
        </div>
    </div>
</div>