config/routes.rb
Rails.application.routes.draw do
  get 'infomations/index'
  devise_for :users
  root to: "events#index"
  get 'events/search'
  resources :events do
    resources :comments, only: :create
  end
  resources :users
  resources :notifications, only: [:index, :destroy]
  
  controller :report do
    get 'report' => 'report#index', as: :report
    get 'report/output', as: :output_report
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :reports

  with_options presence: true do
    validates :title
  end

  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.where(event_id: id).where.not("user_id=? or user_id=?", current_user.id,user_id).select(:user_id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end

    save_notification_comment!(current_user, comment_id, user_id)
    end

    def save_notification_comment!(current_user, comment_id, visited_id)
        notification = current_user.active_notifications.new(
          event_id: id,
          comment_id: comment_id,
          visited_id: visited_id,
          action: 'comment'
        )
        if notification.visitor_id == notification.visited_id
          notification.checked = true
        end
        notification.save if notification.valid?
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :search_event, only: [:index, :search]

  def index
    @events = Event.all.order(start_date: "ASC")
    @user = User.all
    require 'date'
    @date = DateTime.now
    @notification = Notification.all
    set_event_column
    set_user_column
  end

  def show
    @comment = Comment.new
    @comments = @event.comments.includes(:user)
  end

  def new
    @event = Event.new
  end

  def edit
    unless user_signed_in? && current_user.id == @event.user_id
      redirect_to root_path
    end
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @results = @e.result.includes(:user)
    @events = Event.all.order(start_date: "ASC")
  end

  private

    def set_event
      @event = Event.find(params[:id])
    end

    def search_event
      @e = Event.ransack(params[:q])  
    end

    def set_event_column
      @event_title = Event.select("title").distinct
    end

    def set_user_column
      @user_name = User.select("name").distinct
    end

    def event_params
      params.require(:event).permit(:title, :body, :address, :start_date, :end_date).merge(user_id: current_user.id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true, class:"new-event-post") do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class:"title-field" %>
    <%= form.text_field :title, placeholder:"例) ここにタイトルを入力してください(必須)" %>
  </div>

  <div class="field">
    <%= form.label :body, class:"body-field" %>
    <%= form.text_area :body, placeholder:"例) ここに補足の説明文などを入力してください(任意)" %>
  </div>

  <div class="field">
    <%= form.label :address, class:"title-field" %>
    <%= form.text_field :address, placeholder:"例) 東京都新宿区西新宿1-1-3(任意)" %>
  </div>

  <div class="field">
    <%= form.label :start_date, class:"start-date-field" %>
    <%= form.datetime_select :start_date, :use_month_numbers => true, :start_year => Time.now.year, :end_year => Time.now.year + 2, :minute_step => 10 %>
  </div>

  <div class="field">
    <%= form.label :end_date, class:"end-date-field" %>
    <%= form.datetime_select :end_date, :use_month_numbers => true, :start_year => Time.now.year, :end_year => Time.now.year + 2, :minute_step => 10 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="main-container"> 
  <div class="sub-container">
    <h1 class="edit-event-title">Editing Event</h1>

    <%= render 'form', event: @event %>

    <%= link_to 'Show', event_path(@event.id), class:"show-event-btn" %> 

    <div class="return-actions">
      <%= link_to "return Top", root_path, class: "return-top" %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<%= render "shared/header" %>
<p id="notice"><%= notice %></p>

  <% if user_signed_in? %>
    <p class="now-status">You are currently login!!<br>Hello!! <%= current_user.name %>&#x1f60a;</p>
    <%# <p class="top-infomation"><%=link_to "Information on new features", infomations_index_path %>
  <% else %>
    <p class="now-status empty-user">You must be login!!&#x1f622;</p>
  <% end %>
<header>
  <div class="tabbar-header">
    <ul class="menubar">
      <li>
        <a data-id="about">
          <span class="text-menu">MyPage</span>
          <span class="material-icons" id="identity">perm_identity</span>
          <span class="material-icons" id="drop">arrow_drop_down</span>
        </a>
      </li>
      <li>
        <a data-id="service">
          <span class="text-menu">TeamMember</span>
          <span class="material-icons" id="group">groups</span>
          <span class="material-icons" id="drop">arrow_drop_down</span>
        </a>
      </li>
      <li>
        <a data-id="contact">
          <span class="text-menu">Information</span>
          <span class="material-icons" id="info">contact_support</span>
          <span class="material-icons" id="drop">arrow_drop_down</span>
        </a>
      </li>
    </ul>

    <% if user_signed_in? %>
      <section class="content" id="about">
        <span class="material-icons" id="cancel-1">close_fullscreen</span>
        <%= link_to 'MyEventList', user_path(current_user.id), class: "content-list" %>
      </section>
      <section class="content" id="service">
        <span class="material-icons" id="cancel-2">close_fullscreen</span>
        <% @user.each do |u|%>
          <span><%= link_to ",,,#{u.name}", user_path(u.id), class: "content-list" %></span>
        <% end %>
      </section>
      <section class="content" id="contact">
        <span class="material-icons" id="cancel-3">close_fullscreen</span>
        <%= link_to 'Infomation', infomations_index_path, class: "content-list" %>
        <hr class="info-line">
        <br>
        <div class="grad-wrap">
          <p class="information">＞＞最新版リリース内容のお知らせ</p>
          <input id="trigger1" class="grad-trigger" type="checkbox">
          <label class="grad-btn" for="trigger1">続きを読む</label>
          <div class="grad-item">
          平素よりサービス「All Events List」をご利用いただき、誠にありがとうございます。
          <br>
          ユーザー様のご意見を参考にアップデートいたしました。<br>
          以下にて、AllEventsListの追加機能についてご案内いたします。
          <br>
          <br>
          ■リリース日
          <br>
          2020年11月23日
          <br>
          <br>
          1.マイページの住所検索機能をアップデートしました。
          <br>
          ...検索ボタンを押すとMapの検索窓に反映されるよう変更いたしました。
          <br>
          <br>
          ■リリース日
          <br>
          2020年11月18日
          <br>
          <br>
          1. イベント検索機能を実装いたしました。
          <br>
          ...Topページの「Search!」ボタンにてタイトル検索が可能になりました。
          <br>
          <br>
          ■リリース日
          <br>
          2020年11月02日
          <br>
          <br>
          1. コメントの入力機能を追加いたしました。
          <br>
          ...イベント詳細ページにて、コメントを入力します。
          <br>
          ...コメントはトップページのアラートボタンに通知されます。
          <br>
          ...未読のコメントがある場合、赤い点がつきます。
          <br>
          <br>
          2. 住所検索機能を追加いたしました。
          <br>
          ...マイページにて住所の検索が可能になりました。
          <br>
          ...「MyPage」、及び「TeamMenber」から、各ページに移動し検索ができます。
          <br>
          ...ご訪問先の住所検索などにご利用ください。
          <br>
          <br>
          3. トップページのイベントの表示順が変更になりました。
          <br>
          ...今までは、作成したイベント順であったのに対して、<br>イベントの開始時刻(start_date)の昇順に変更いたしました。
          <br>
          <br>
          4. 時間を過ぎたイベントを非表示にいたしました。
          <br>
          ...トップページのイベントは時間を過ぎたら非表示になるよう変更いたしました。
          <br>
          ...ただし、これまで通りマイページでは全てのイベントが確認できますので、<br>必要に応じて「完了」をクリックして頂くようお願い申し上げます。
          <br>
          <br>
          5. イベントの帳票出力機能を実装いたしました。
          <br>
          ...トップページの緑のアイコンから移動し「Commit」ボタンをクリックし保存します。
          <br>
          <br>
          以上、今後も「All Events List」をよろしくお願いいたします。
          </div>
        </div>
      </section>
    <% end %>
  </div>

  <% if user_signed_in? %>
    <div class="report-header">
      <%= link_to report_path do%>
        <span class="material-icons" id="snippet">text_snippet</span>
      <% end %>
    </div>

    <div class="alert-header">
      <%= link_to notifications_path do %>
        <span class="material-icons" id="alert">notification_important</span> 
        <% @notification.each do |notification| %>
          <% if (notification.visited_id == current_user.id) && notification.checked == false %>
            <span class="material-icons" id="on-alert">fiber_manual_record</span>
            <% break %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <div class="clock-header" id="clock_frame">
    <span class="material-icons" id="clock">schedule</span>
    <span id="clock_time"></span>
  </div>

  <div class="navbar-header">
    <span class="material-icons" id="open">menu</span>
  </div>

</header>  

<div class="overlay">
  <span class="material-icons" id="close">close</span>
  <nav>
    <ul>
    <% unless user_signed_in? %>
      <li><%= link_to "SignUp", new_user_registration_path %></li>
      <li><%= link_to "LogIn", new_user_session_path %></li>
    <% else %>
      <li><%= link_to "LogOut", destroy_user_session_path, method: :delete %></li>
      <li><%= link_to "Account", edit_user_path(current_user) %></li>
      <li><%= link_to "MyPage", user_path(current_user.id) %></li>
      <li><%= link_to "NewEvent", new_event_path %></li>
      <li><%= link_to "Infomation", infomations_index_path %></li>
    <% end %>
    </ul>
</div>

<% if user_signed_in? %>
<div class="calender-container">
  <div id="calendar"></div>
</div>
  <div class="search-schedule">
    <%= search_form_for @e, url: events_search_path do |f| %>
      <%= f.collection_select :title_eq, @events, :title, :title, include_blank: ' ', class:"search-title" %>
      <%= f.submit 'Search!', id:"search_data" %>
    <% end %>
  </div>
<% end %>

<table class="schedule-table">
  <% if user_signed_in? %>
  <thead class="schedule-thead">
    <tr>
      <th class="caption caption-title">Title</th>
      <th class="caption">Start date</th>
      <th class="caption">End date</th>
      <th class="caption">Post user</th>
      <th class="caption" colspan="3">Button</th>
    </tr>
  </thead>

  <tbody class="schedule-tbody">
    <% @events.each do |event| %>
      <% if @date <= event.start_date %>
        <tr>
          <td class="event-td"><%= event.title %></td>
          <td><%= event.start_date.to_s(:datetime) %></td>
          <td><%= event.end_date.to_s(:datetime) %></td>
          <td><%= event.user.name %></td>
          <td><%= link_to '詳細', event, class:"event-btn" %></td>
          <% if current_user.id == event.user.id %>
            <td><%= link_to '編集', edit_event_path(event), class:"event-btn"  %></td>
            <td><%= link_to '削除', event, class:"event-btn", method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
            <td><a class="event-btn">-</a>
            <td><a class="event-btn">-</a>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<div class='addevent-btn'>
    <%= link_to new_event_path, class: "addevent-btn-text" do %>
      <p>New Event</p>
      <span class="material-icons" id="event-icon">add_task</span>
    <% end %>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/events/new.html.erb
<div class="main-container">
  <div class="sub-container">
    <h1 class="new-event-title">New Event</h1>

    <%= render 'form', event: @event %>

    <div class="return-actions">
      <%= link_to "return Top", root_path, class: "return-top" %>
    </div>
  </div>
</div>

app/views/events/search.html.erb
<h3 class="output-header">
Search Result
<span class="output-header-span">(検索結果)</span>
</h3>

<table class="schedule-table">
  <thead class="schedule-thead">
    <tr>
      <th class="caption caption-title">Title</th>
      <th class="caption">Start date</th>
      <th class="caption">End date</th>
      <th class="caption">Post user</th>
      <th class="caption">Address</th>
      <th class="caption" colspan="3">Button</th>
    </tr>
  </thead>

  <tbody class="schedule-tbody">
    <% if @results.length !=0 %>
      <% @results.each do |result| %>
        <tr>
          <td><%= result.title %></td>
          <td><%= result.start_date.to_s(:datetime) %></td>
          <td><%= result.end_date.to_s(:datetime) %></td>
          <td><%= result.user.name %></td>
          <td><button class="btn-input" id="btn"><span class="material-icons" id="search-address">search</span></button>
            <span class="black-address" id="black-address"><%= result.address %></span>
          </td>
          <td><%= link_to '詳細', event_path(result.id), class:"event-btn" %></td>
          <% if current_user.id == result.user.id %> 
            <td><%= link_to '編集', edit_event_path(result.id), class:"event-btn"  %></td>
            <td><%= link_to '削除', event_path(result.id), class:"event-btn", method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
            <td><a class="event-btn">-</a>
            <td><a class="event-btn">-</a>
          <% end %>  
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<div class="actions report-return">
  <%= link_to "return Top", root_path, class: "return-top" %>
</div>

<div class="search-address">
  <h3 class="pad">Search Address</h3>
</div>
<h4 class="discription">
  Click <span class="material-icons discription-search" id="search-address">search</span> to add Search Box
</h4>

<input
  id="pac-input"
  class="controls"
  type="text"
  placeholder="Search Box"/>
<div id="map"></div>

app/views/events/show.html.erb
<div class="main-container">
  <div class="sub-container">
    <p id="notice"><%= notice %></p>

    <h1 class="show-event-title">Show Event</h1>

    <p>
      <strong>Title:</strong>
      <%= @event.title %>
    </p>

    <br>

    <p class="show-event-body">
      <strong>Body:</strong>
      <%= @event.body %>
    </p>
    <br>
    <p class="show-event-address">
      <strong>Address:</strong>
      <%= @event.address %>
    </p>
    <br>
    <p>
      <strong>Start date:</strong>
      <%= @event.start_date.to_s(:datetime) %>
    </p>
    <p>
      <strong>End date:</strong>
      <%= @event.end_date.to_s(:datetime) %>
    </p>

      <br>
      <% if user_signed_in? && current_user.id == @event.user_id %>
        <%= link_to 'Edit', edit_event_path(@event), class:"show-event-btn edit-btn" %> 
      <% end %>

    <hr class="line"> 
    <div class="comments">
          <h4 class="comment-field">＜All comments＞</h4>
          <% if @comments %>
            <% @comments.each do |comment| %>
              <p>
                <strong><%= link_to comment.user.name, "/users/#{comment.user_id}" %>：</strong>
                <%= comment.text %>
              </p>
            <% end %>
          <% end %>
        </div>


      <div class="container">
        <% if current_user %>
          <%= form_with(model: [@event, @comment], local: true, class:"comment-form") do |form| %>
            <%= form.text_area :text, placeholder: "Let's comment!!", rows: "2", class:"comment-form-area" %>
            <%= form.submit "SEND" %>
          <% end %>
        <% end %>
      </div>

    <div class="return-actions">
      <%= link_to "return Top", root_path, class: "return-top " %>
    </div>
  </div>
</div>