config/routes.rb
Rails.application.routes.draw do
  get 'infomations/index'
  devise_for :users
  root to: "events#index"
  get 'events/search'
  resources :events do
    resources :comments, only: :create
  end
  resources :users
  resources :notifications, only: [:index, :destroy]
  
  controller :report do
    get 'report' => 'report#index', as: :report
    get 'report/output', as: :output_report
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :event

  def initialize(year, month)
    @start_date = Date.new(year, month, 1)
    @end_date = @start_date + 1.month - 1.day
  end
  def dates
    @start_date..@end_date
  end
  def events
    @events ||= Event.all.to_a
  end

  def events_amount_on(date, event)
    Event.where(start_date: date)
        .where(event_id: event.id)
  end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def index
  end

  def output
    # @report = Report.new(params[:year].to_i, params[:month].to_i)
  end

end

app/helpers/report_helper.rb
module ReportHelper
end

app/views/report/index.html.erb
<div class="main-container">
  <div class="sub-container">
    <h3 class="output-header">
      All Events output
      <span class="output-header-span">(イベント一覧EXCEL出力)</span>
    </h3>
    <%= form_tag output_report_path(format: :xls), method: :get do %>
      <%# <p> %>
        <%# <%= label_tag :year, '年' %> 
        <%# <%= text_field_tag :year %>
      <%# </p>
      <p> %>
        <%# <%= label_tag :month, '月' %>
        <%# <%= text_field_tag :month %>
      <%# </p> %>
      <%= submit_tag 'Export!', class:'output-submit' %>
    <% end %>

    <div class="actions report-return">
      <%= link_to "return Top", root_path, class: "return-top" %>
    </div>
  </div>
</div>

app/views/report/output.xls.erb
<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:html="http://www.w3.org/TR/REC-html40">
 <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
  <Author>村上 拓海</Author>
  <LastAuthor>村上 拓海</LastAuthor>
  <Created>2020-11-02T01:54:21Z</Created>
  <LastSaved>2020-11-02T02:30:01Z</LastSaved>
  <Version>16.00</Version>
 </DocumentProperties>
 <OfficeDocumentSettings xmlns="urn:schemas-microsoft-com:office:office">
  <AllowPNG/>
 </OfficeDocumentSettings>
 <ExcelWorkbook xmlns="urn:schemas-microsoft-com:office:excel">
  <WindowHeight>16260</WindowHeight>
  <WindowWidth>14400</WindowWidth>
  <WindowTopX>14400</WindowTopX>
  <WindowTopY>460</WindowTopY>
  <ProtectStructure>False</ProtectStructure>
  <ProtectWindows>False</ProtectWindows>
 </ExcelWorkbook>
 <Styles>
  <Style ss:ID="Default" ss:Name="Normal">
   <Alignment ss:Vertical="Center"/>
   <Borders/>
   <Font ss:FontName="游ゴシック" x:CharSet="128" ss:Size="12" ss:Color="#000000"/>
   <Interior/>
   <NumberFormat/>
   <Protection/>
  </Style>
  <Style ss:ID="s71">
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
  </Style>
  <Style ss:ID="s72">
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <NumberFormat ss:Format="Short Date"/>
  </Style>
  <Style ss:ID="s76">
   <Alignment ss:Vertical="Center"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font ss:FontName="游ゴシック" x:CharSet="128" ss:Size="12" ss:Color="#000000"
    ss:Bold="1"/>
  </Style>
 </Styles>
 <Worksheet ss:Name="Sheet1">
  <Table x:FullRows="1" ss:DefaultColumnWidth="75" ss:DefaultRowHeight="20">
   <Column ss:Index="2" ss:Width="229"/>
   <Column ss:Index="5" ss:Width="108"/>
   <Row ss:AutoFitHeight="0" ss:Height="43">
    <Cell ss:StyleID="s76"><PhoneticText
      xmlns="urn:schemas-microsoft-com:office:excel">イティ</PhoneticText><Data
      ss:Type="String">イベント一覧</Data></Cell>
    <Cell ss:StyleID="s76"/>
    <Cell ss:StyleID="s76"/>
    <Cell ss:StyleID="s76"/>
    <Cell ss:StyleID="s76"/>
   </Row>

   <Row>
  <%# <% Event.all.each do |e| %> 
    <Cell ss:StyleID="s71"><Data ss:Type="String">title</Data></Cell>
    <Cell ss:StyleID="s71"><Data ss:Type="String">body</Data></Cell>
    <Cell ss:StyleID="s71"><Data ss:Type="String">start_date</Data></Cell>
    <Cell ss:StyleID="s71"><Data ss:Type="String">end_date</Data></Cell>
    <Cell ss:StyleID="s71"><Data ss:Type="String">post_user</Data></Cell>
  <%# <% end %> 
   </Row>

  <% Event.all.each do |e| %>
  <%# <% ("2020-11-01".."2020-11-07").each do |date| %> 
   <Row>
    <Cell ss:StyleID="s71"><Data ss:Type="String"><%= e.title %></Data></Cell>
    <Cell ss:StyleID="s71"><PhoneticText
      xmlns="urn:schemas-microsoft-com:office:excel"></PhoneticText><Data
      ss:Type="String"><%= e.body %></Data></Cell>
    <Cell ss:StyleID="s71"><Data ss:Type="String"><%= e.start_date.to_s %></Data></Cell>
    <Cell ss:StyleID="s71"><Data ss:Type="String"><%= e.end_date.to_s %></Data></Cell>
    <Cell ss:StyleID="s71"><Data ss:Type="String"><%= e.user.name %></Data></Cell>
   </Row>
  <% end %>
  </Table>
  <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">
   <PageSetup>
    <Header x:Margin="0.3"/>
    <Footer x:Margin="0.3"/>
    <PageMargins x:Bottom="0.75" x:Left="0.7" x:Right="0.7" x:Top="0.75"/>
   </PageSetup>
   <Selected/>
   <Panes>
    <Pane>
     <Number>3</Number>
     <ActiveRow>15</ActiveRow>
     <ActiveCol>1</ActiveCol>
    </Pane>
   </Panes>
   <ProtectObjects>False</ProtectObjects>
   <ProtectScenarios>False</ProtectScenarios>
  </WorksheetOptions>
 </Worksheet>
</Workbook>